- name: create Jenkins jobs
  hosts: localhost
  connection: local
  vars:
    mp_jobs:
      - roboshop-terraform
      - cart
      - catalogue
      - user
      - payment
      - shipping
      - frontend
  roles:
    - jenkins-jobs